### ISSUE TITLE
How do I style an individual path in an SVG with CSS?

### ISSUE THREAD

**Issue by JDomleo** [nuxt-community/svg-sprite-module#170]
![image](https://user-images.githubusercontent.com/43371432/86030828-e6b26600-ba2c-11ea-9bd9-8f5df4143cf2.png)

The SVG is hidden inside `shadow-root`.

I have some SCSS, that I want to change the colour of each path when the SVG is hovered:

```scss
svg {
  &:hover {
    path {
      &:nth-child(1) {
        fill: #00C58E;
      }

      &:nth-child(2) {
        fill: #2F495E;
      }

      &:nth-child(3) {
        fill: #108775;
      }
    }
  }
}
```

But this doesn't work because of `shadow-root`. What's the best way to achieve this? 🙂
